Comment out broken test since @andersliland says so

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -2,14 +2,10 @@
 name: Release
 
 on:
-  workflow_run:
+  push:
     branches:
       - main
       - release/**
-    workflows:
-      - '[ci] Test & Build'
-    types:
-      - completed
 
 jobs:
   update_action_image:
@@ -51,42 +47,42 @@ jobs:
           repository: .
           commit_message: Release ${{ steps.gitversion.outputs.version }}
 
-  test_main:
-    name: Test velo action on main
-    runs-on: ubuntu-20.04
-    needs:
-      - update_action_image
-    steps:
-      - name: Checkout ${{ needs.update_action_image.outputs.commit_hash }}
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ needs.update_action_image.outputs.commit_hash }}
-
-      - name: Test velo generate version from main
-        uses: kolonialno/velo-action@main
-        id: velo
-
-      - name: Get git short rev
-        shell: bash
-        id: short_ref
-        run: |
-          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
-
-      - name: Fail if version command is not correct
-        shell: bash
-        if: ${{ steps.velo.outputs.version != steps.short_ref.outputs.sha }}
-        run: |
-          echo "Velo generated version is: ${{ steps.velo.outputs.version }}"
-          echo "Git sha is: ${{ steps.short_ref.outputs.sha }}"
-          echo "Version is wrong"
-          exit 1
+#  test_main:
+#    name: Test velo action on main
+#    runs-on: ubuntu-20.04
+#    needs:
+#      - update_action_image
+#    steps:
+#      - name: Checkout ${{ needs.update_action_image.outputs.commit_hash }}
+#        uses: actions/checkout@v3
+#        with:
+#          ref: ${{ needs.update_action_image.outputs.commit_hash }}
+#
+#      - name: Test velo generate version from main
+#        uses: kolonialno/velo-action@main
+#        id: velo
+#
+#      - name: Get git short rev
+#        shell: bash
+#        id: short_ref
+#        run: |
+#          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
+#
+#      - name: Fail if version command is not correct
+#        shell: bash
+#        if: ${{ steps.velo.outputs.version != steps.short_ref.outputs.sha }}
+#        run: |
+#          echo "Velo generated version is: ${{ steps.velo.outputs.version }}"
+#          echo "Git sha is: ${{ steps.short_ref.outputs.sha }}"
+#          echo "Version is wrong"
+#          exit 1
 
   release:
     name: Create Github release
     runs-on: ubuntu-20.04
     needs:
       - update_action_image
-      - test_main
+#      - test_main
     steps:
       - name: Checkout ${{ needs.update_action_image.outputs.commit_hash }}
         uses: actions/checkout@v3
